# Generated by Django 3.0.8 on 2020-08-01 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('do_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Do Date')),
                ('status', models.CharField(choices=[('w', 'Working'), ('d', 'Done'), ('c', 'Cancel')], default='w', max_length=1)),
            ],
            options={
                'ordering': ('-do_date',),
            },
        ),
    ]
